# yml template to dockerise a node.js app
version: '3'
services:
    appservice:
        container_name: AppGeosoft2
        build:
          dockerfile: ./Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - mydata:/usr/src/app/myfiles
            - ./public/beispieldaten:/usr/src/app/beispieldaten

    rservice:
        container_name: RService
        build:
            dockerfile: ./r-backend/Dockerfile
        ports:
            - '7001:8000'
        restart: always
        volumes:
            - mydata:/usr/src/app/myfiles
    
volumes:
    mydata:
    beispieldaten:
